leave-management/Controllers/LeaveRequestController.cs
using AutoMapper;
using leave_management.Contracts;
using leave_management.Data;
using leave_management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace leave_management.Controllers
{
    [Authorize]
    public class LeaveRequestController : Controller
    {
        private readonly ILeaveRequestRepository _leaveRequestRepository;
        private readonly ILeaveTypeRepository _leaveTypeRepository;
        private readonly ILeaveAllocationRepository _leaveAllocationRepository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<IdentityUser> _userManager;

        public LeaveRequestController(
            ILeaveRequestRepository leaveRequestRepository,
            ILeaveTypeRepository leaveTypeRepository,
            ILeaveAllocationRepository leaveAllocationRepository,
            IUnitOfWork unitOfWork,
            IMapper mapper,
            UserManager<IdentityUser> userManager
            )
        {
            _leaveRequestRepository = leaveRequestRepository;
            _leaveTypeRepository = leaveTypeRepository;
            _leaveAllocationRepository = leaveAllocationRepository;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
        }

        [Authorize(Roles = "Administrator")]
        // GET: LeaveRequestController
        public async Task<ActionResult> Index()
        {
            //var leaveRequests = await _leaveRequestRepository.FindAll();

            var leaveRequests = await _unitOfWork.LeaveRequests.FindAll
                (
                    include: q => q.Include(lr => lr.RequestingEmployee).Include(lr => lr.LeaveType) 
                    /*includes: new List<string> { "RequestingEmployee", "LeaveType"}*/
                );

            var leaveRequestsVM = _mapper.Map<List<LeaveRequestVM>>(leaveRequests);

            var adminLeaveRequestViewVM = new AdminLeaveRequestVM
            {
                TotalRequests = leaveRequestsVM.Count,
                ApprovedRequests = leaveRequestsVM.Count(r => r.Approved == true),
                PendingRequests = leaveRequestsVM.Count(r => r.Approved == null),
                RejectRequests = leaveRequests.Count(r => r.Approved == false),
                LeaveRequests = leaveRequestsVM
            };
            return View(adminLeaveRequestViewVM);
        }

        // GET: LeaveRequestController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            //var leaveRequest = await _leaveRequestRepository.FindById(id);

            var leaveRequest = await _unitOfWork.LeaveRequests.Find
                (
                    expression: lr => lr.Id == id,
                    include: q => q.Include(lr => lr.ApprovedBy).Include(lr => lr.RequestingEmployee).Include(lr => lr.LeaveType)
                    //new List<string> { "ApprovedBy", "RequestingEmployee", "LeaveType" }
                );
            var leaveRequestVM = _mapper.Map<LeaveRequestVM>(leaveRequest);
            return View(leaveRequestVM);
        }

        public async Task<ActionResult> ApproveRequest(int id)
        {
            try
            {
                var admin = _userManager.GetUserAsync(User).Result;
                //var leaveRequest = await _leaveRequestRepository.FindById(id);
                //var leaveAllocation = await _leaveAllocationRepository.GetLeaveAllocationByEmployeeAndLeaveType(leaveRequest.RequestingEmployeeId, leaveRequest.Id);

                var period = DateTime.Now.Year;
                var leaveRequest = await _unitOfWork.LeaveRequests.Find(lr => lr.Id == id);
                var leaveAllocation = await _unitOfWork.LeaveAllocations.Find
                    (
                        la => la.EmployeeId == leaveRequest.RequestingEmployeeId
                           && la.LeaveTypeId == leaveRequest.Id
                           && la.Period == period
                    );

                leaveRequest.Approved = true;
                leaveRequest.ApprovedById = admin.Id;
                leaveRequest.DateActioned = DateTime.Now;

                int dayRequested = (int)(leaveRequest.EndDate - leaveRequest.StartDate).TotalDays;
                leaveAllocation.NumberOfDays -= dayRequested;

                //await _leaveRequestRepository.Update(leaveRequest);
                //await _leaveAllocationRepository.Update(leaveAllocation);

                _unitOfWork.LeaveRequests.Update(leaveRequest);
                _unitOfWork.LeaveAllocations.Update(leaveAllocation);
                await _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<ActionResult> RejectRequest(int id)
        {
            try
            {
                //var leaveRequest = await _leaveRequestRepository.FindById(id);

                var leaveRequest = await _unitOfWork.LeaveRequests.Find(lr => lr.Id == id);
                var admin = _userManager.GetUserAsync(User).Result;

                leaveRequest.Approved = false;
                leaveRequest.ApprovedById = admin.Id;
                leaveRequest.DateActioned = DateTime.Now;

                //await _leaveRequestRepository.Update(leaveRequest);
                _unitOfWork.LeaveRequests.Update(leaveRequest);
                await _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: LeaveRequestController/Create
        public async Task<ActionResult> Create()
        {
            //var leaveTypes = await _leaveTypeRepository.FindAll();
            var leaveTypes = await _unitOfWork.LeaveTypes.FindAll();
            var leaveTypeItems = leaveTypes.Select(lt => new SelectListItem
            {
                Text = lt.Name,
                Value = lt.Id.ToString()
            });

            var createLeaveRequestVM = new CreateLeaveRequestVM
            {
                LeaveTypes = leaveTypeItems
            };
            return View(createLeaveRequestVM);
        }

        // POST: LeaveRequestController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLeaveRequestVM createLeaveRequestVM)
        {
            try
            {
                var startDate = Convert.ToDateTime(createLeaveRequestVM.StartDate);
                var endDate = Convert.ToDateTime(createLeaveRequestVM.EndDate);

                //var leaveTypes = await _leaveTypeRepository.FindAll();

                var leaveTypes = await _unitOfWork.LeaveTypes.FindAll();
                var leaveTypeItems = leaveTypes.Select(lt => new SelectListItem
                {
                    Text = lt.Name,
                    Value = lt.Id.ToString()
                });

                createLeaveRequestVM.LeaveTypes = leaveTypeItems;

                if (!ModelState.IsValid)
                {
                    return View(createLeaveRequestVM);
                }

                if (DateTime.Compare(startDate, endDate) > 1)
                {
                    ModelState.AddModelError("", "Start Date cannot be further in the future than End Date");
                    return View(createLeaveRequestVM);
                }

                var employee = _userManager.GetUserAsync(User).Result;
                //var leaveAllocation = await _leaveAllocationRepository.GetLeaveAllocationByEmployeeAndLeaveType(employee.Id, createLeaveRequestVM.LeaveTypeId);

                var period = DateTime.Now.Year;
                var leaveAllocation = await _unitOfWork.LeaveAllocations.Find
                    (
                        la => la.EmployeeId == employee.Id
                           && la.LeaveTypeId == createLeaveRequestVM.LeaveTypeId
                           && la.Period == period
                    );

                if (leaveAllocation is null)
                {
                    ModelState.AddModelError("", "You have no days left");
                }

                var dayRequested = (int)(endDate.Date - startDate.Date).TotalDays;
                if (dayRequested > leaveAllocation.NumberOfDays)
                {
                    ModelState.AddModelError("", "You do not sufficient days for this request");
                    return View(createLeaveRequestVM);
                }

                var leaveRequestVM = new LeaveRequestVM
                {
                    RequestingEmployeeId = employee.Id,
                    StartDate = startDate,
                    EndDate = endDate,
                    Approved = null,
                    DateRequested = DateTime.Now,
                    DateActioned = DateTime.Now,
                    LeaveTypeId = createLeaveRequestVM.LeaveTypeId,
                    RequestComments = createLeaveRequestVM.RequestComments
                };

                var leaveRequest = _mapper.Map<LeaveRequest>(leaveRequestVM);

                //bool isSuccess = await _leaveRequestRepository.Create(leaveRequest);
                //if (!isSuccess)
                //{
                //    ModelState.AddModelError("", "Something went wrong with submitting your record");
                //    return View(createLeaveRequestVM);
                //}

                await _unitOfWork.LeaveRequests.Create(leaveRequest);
                await _unitOfWork.Save();

                

leave-management/Controllers/LeaveTypeController.cs
using AutoMapper;
using leave_management.Contracts;
using leave_management.Data;
using leave_management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace leave_management.Controllers
{
    [Authorize]
    public class LeaveTypeController : Controller
    {
        private readonly ILeaveTypeRepository _leaveTypeRepository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public LeaveTypeController(ILeaveTypeRepository leaveTypeRepository, IUnitOfWork unitOfWork,IMapper mapper)
        {
            _leaveTypeRepository = leaveTypeRepository;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        // GET: LeaveTypeController
        public async Task<ActionResult> Index()
        {
            //var leaveTypes = await _leaveTypeRepository.FindAll();
            var leaveTypes = await _unitOfWork.LeaveTypes.FindAll();
            var model = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveTypes.ToList());
            return View(model);
        }

        // GET: LeaveTypeController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            //var isExists = await _leaveTypeRepository.IsExists(id);

            var isExists = await _unitOfWork.LeaveTypes.IsExists(lt => lt.Id == id);
            if (!isExists)
            {
                return NotFound();
            }

            //var leaveType = await _leaveTypeRepository.FindById(id);

            var leaveType = await _unitOfWork.LeaveTypes.Find(lt => lt.Id == id);
            var leaveTypeVM = _mapper.Map<LeaveTypeVM>(leaveType);

            return View(leaveTypeVM);
        }

        [Authorize(Roles ="Administrator")]
        // GET: LeaveTypeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LeaveTypeVM leaveTypeVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(leaveTypeVM);
                }

                var leaveType = _mapper.Map<LeaveType>(leaveTypeVM);
                leaveType.DateCreated = DateTime.Now;

                //var isSuccess = await _leaveTypeRepository.Create(leaveType);
                //if (!isSuccess)
                //{
                //    ModelState.AddModelError("", "Something went wrong...");
                //    return View(leaveTypeVM);
                //}

                await _unitOfWork.LeaveTypes.Create(leaveType);
                await _unitOfWork.Save();
                

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(leaveTypeVM);
            }
        }

        [Authorize(Roles = "Administrator")]
        // GET: LeaveTypeController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            //var isExists = await _leaveTypeRepository.IsExists(id);
            var isExists = await _unitOfWork.LeaveTypes.IsExists(lt => lt.Id == id);
            if (!isExists)
            {
                return NotFound();
            }

            //var leaveType = await _leaveTypeRepository.FindById(id);

            var leaveType = await _unitOfWork.LeaveTypes.Find(lt => lt.Id == id);
            var leaveTypeVM = _mapper.Map<LeaveTypeVM>(leaveType);
            return View(leaveTypeVM);
        }


        [Authorize(Roles = "Administrator")]
        // POST: LeaveTypeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(LeaveTypeVM leaveTypeVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(leaveTypeVM);
                }

                var leaveType = _mapper.Map<LeaveType>(leaveTypeVM);

                //var isSuccess = await _leaveTypeRepository.Update(leaveType);     
                //if (!isSuccess)
                //{
                //    ModelState.AddModelError("","Something went wrong...");
                //    return View(leaveTypeVM);
                //}

                _unitOfWork.LeaveTypes.Update(leaveType);
                await _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(leaveTypeVM);
            }
        }

        [Authorize(Roles = "Administrator")]
        // GET: LeaveTypeController/Delete/5
        public async Task<ActionResult> Delete(/*LeaveTypeVM leaveTypeVM*/int id)
        {
            //----------Solution 1------------//

            //if (leaveTypeVM != null)
            //{
            //    var leaveType = _mapper.Map<LeaveType>(leaveTypeVM);
            //    var isSucess = _leaveTypeRepository.Delete(leaveType);
            //    if (!isSucess)
            //    {
            //        ModelState.AddModelError("", "Something went wrong...");
            //        return View();
            //    }
            //}
            //return RedirectToAction(nameof(Index));


            //----------Solution 2------------//

            //var leaveType = await _leaveTypeRepository.FindById(id);

            var leaveType = await _unitOfWork.LeaveTypes.Find(lt => lt.Id == id);
            if (leaveType == null)
            {
                return NotFound();
            }

            //var isSuccess = await _leaveTypeRepository.Delete(leaveType);
            //if (!isSuccess)
            //{
            //    return BadRequest();
            //}

            _unitOfWork.LeaveTypes.Delete(leaveType);
            await _unitOfWork.Save();

            return RedirectToAction(nameof(Index));


            //----------Solution 3------------//

            //if (!_leaveTypeRepository.isExists(id))
            //{
            //    return NotFound();
            //}
            //var leaveType = _leaveTypeRepository.FindById(id);
            //var leaveTypeVM = _mapper.Map<LeaveTypeVM>(leaveType);
            //return View(leaveTypeVM);
        }


        [Authorize(Roles = "Administrator")]
        // POST: LeaveTypeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, LeaveTypeVM leaveTypeVM)
        {
            try
            {
                //var leaveType = await _leaveTypeRepository.FindById(id);

                var leaveType = await _unitOfWork.LeaveTypes.Find(lt => lt.Id == id);
                if (leaveType == null)
                {
                    return NotFound();
                }

                //var isSuccess =  await _leaveTypeRepository.Delete(leaveType);
                //if (!isSuccess)
                //{
                //    return View(leaveTypeVM);
                //}

                _unitOfWork.LeaveTypes.Delete(leaveType);
                await _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(leaveTypeVM);
            }
        }
    }
}

leave-management/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - leave_management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">leave_management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LeaveRequest" asp-action="Create">Apply for Leave</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LeaveRequest" asp-action="MyLeave">My Leave</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true">
                                        Manage
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item text-dark" asp-controller="LeaveType" asp-action="Index">Leave Types</a>
                                        <a class="dropdown-item text-dark" asp-controller="LeaveAllocation" asp-action="Index">Leave Allocations</a>
                                        <a class="dropdown-item text-dark" asp-controller="LeaveRequest" asp-action="Index">Leave Requests</a>
                                        <a class="dropdown-item text-dark" asp-controller="LeaveAllocation" asp-action="ListEmployees">Employees</a>
                                    </div>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - leave_management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>